-- Add level to missions
ALTER TABLE public.missions
ADD COLUMN level INT NOT NULL DEFAULT 1;

-- Create clan_events table
CREATE TABLE public.clan_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clan_id UUID NOT NULL REFERENCES public.clans(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes
CREATE INDEX ON public.clan_events (clan_id);
CREATE INDEX ON public.clan_events (created_at DESC);

-- RLS Policies for clan_events
ALTER TABLE public.clan_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow clan members to view events"
ON public.clan_events
FOR SELECT
USING (
    clan_id IN (
        SELECT clan_id FROM public.profiles WHERE id = auth.uid()
    )
);

CREATE POLICY "Allow service_role to insert events"
ON public.clan_events
FOR INSERT
WITH CHECK (false); -- Disallow direct client insertion

-- Allow read access to territories for all authenticated users
DROP POLICY IF EXISTS "Allow authenticated users to view territories" ON public.territories;
CREATE POLICY "Allow authenticated users to view territories"
ON public.territories
FOR SELECT
TO authenticated
USING (true);
